# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-alois',
                'doc_host': 'https://aloiswirth.github.io',
                'git_url': 'https://github.com/aloiswirth/nbdev-hello-alois',
                'lib_path': 'nbdev_hello_alois'},
  'syms': {'nbdev_hello_alois.core': {'nbdev_hello_alois.core.foo': ('core.html#foo', 'nbdev_hello_alois/core.py')}}}
