# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 4
suits = ["♦️","❤️","♠️","♣️"]
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 12
class Card:
    "A playing card created by passing in a `rank` from `ranks` and a `suit` to `suits`!"
    def __init__(self,
                 suit:int,   # an index into `suits`
                 rank:int):  # an index into `ranks`
        self.suit, self.rank = suit, rank
    def __str__(self):
        return f'{ranks[self.rank]}{suits[self.suit]}'
    __repr__ = __str__
    def __eq__(self, a):
        return (self.suit, self.rank) == (a.suit, a.rank)
    def __lt__(self, a): 
        return (self.suit,self.rank)<(a.suit,a.rank)
    def __gt__(self, a): 
        return (self.suit,self.rank)>(a.suit,a.rank)
