# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/35_elementary_test.ipynb.

# %% auto 0
__all__ = ['config', 'topsecret']

# %% ../nbs/35_elementary_test.ipynb 2
import configparser

# %% ../nbs/35_elementary_test.ipynb 3
config = configparser.ConfigParser()
config['DEFAULT'] = {'ServerAliveInterval': '45',
                     'Compression': 'yes',
                     'CompressionLevel': '9'}
config['bitbucket.org'] = {}
config['bitbucket.org']['User'] = 'hg'
config['topsecret.server.com'] = {}
topsecret = config['topsecret.server.com']
topsecret['Port'] = '50022'     # mutates the parser
topsecret['ForwardX11'] = 'no'  # same here
config['DEFAULT']['ForwardX11'] = 'yes'
with open('conf_pars_example.ini', 'w') as configfile:
  config.write(configfile)

# %% ../nbs/35_elementary_test.ipynb 5
config = configparser.ConfigParser()
config.sections()
