# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['new_variable', 'foo', 'say_hello']

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
new_variable = 1+1
print(new_variable ** 2)

# %% ../nbs/00_core.ipynb 6
def say_hello(to):
    "Say hello to someone"
    return f'Hello {to}!'    

# %% ../nbs/00_core.ipynb 7
say_hello('Michael')

# %% ../nbs/00_core.ipynb 8
say_hello('Alois')
