# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/30_alternativelogging.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/30_alternativelogging.ipynb 3
from loguru import logger

logger.remove(0)

logger.add('local_log.log')

# %% ../nbs/30_alternativelogging.ipynb 8
import sys
import logging

# %% ../nbs/30_alternativelogging.ipynb 9
logging.basicConfig(filename="training.log", encoding="utf-8", level=logging.DEBUG, filemode='a', format='%(asctime)s %(levelname)s %(message)s' )
logging.warning("this is a first warning entry")
