# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/25_object_storage.ipynb.

# %% auto 0
__all__ = ['user', 'pw', 'httpClient']

# %% ../nbs/25_object_storage.ipynb 2
import urllib3
from minio import Minio
import pickle
import getpass
import sys


# %% ../nbs/25_object_storage.ipynb 5
user = 'fake'
pw = 'pw_fake'

# %% ../nbs/25_object_storage.ipynb 6
httpClient = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs='./ca/cacert.crt')
