# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_quick_test.ipynb.

# %% auto 0
__all__ = ['mylog']

# %% ../nbs/02_quick_test.ipynb 3
import loguru
from .card import *


# %% ../nbs/02_quick_test.ipynb 4
mylog = loguru.logger
mylog.info('this is a log')


