# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/45_smote.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/45_smote.ipynb 3
# import necessary modules 
import pandas  as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# %% ../nbs/45_smote.ipynb 5
# data = pd.read_csv('smote_creditcard.csv')
# print(data.info())
# print(data.describe())
