# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/55_tfidf.ipynb.

# %% auto 0
__all__ = ['corpus', 'vectorizer', 'X', 'Z']

# %% ../nbs/55_tfidf.ipynb 2
from sklearn.feature_extraction.text import TfidfVectorizer

# %% ../nbs/55_tfidf.ipynb 3
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
    'why do I do this',
    'Where does the universe come from?',
    'how will the Vectorizer matrix look like?'
]
vectorizer = TfidfVectorizer(max_features=10)
X = vectorizer.fit_transform(corpus)


# %% ../nbs/55_tfidf.ipynb 4
vectorizer.get_feature_names_out()


# %% ../nbs/55_tfidf.ipynb 5
print(X.shape)
print(X)

# %% ../nbs/55_tfidf.ipynb 6
Z = vectorizer.fit(corpus)

# %% ../nbs/55_tfidf.ipynb 7
Z.idf_

